### ISSUE TITLE
iPhone 6+ Does Not Display My Tree Maps or Nearby Tree Maps

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#246]
Here's my tree maps page on an iPhone 6+
![img_5057](https://cloud.githubusercontent.com/assets/12401491/11692285/c818722e-9e6c-11e5-8224-76861add9233.jpg)
And here it is (same account) on an iPhone 6
![img_5061](https://cloud.githubusercontent.com/assets/12401491/11692369/29747d4c-9e6d-11e5-8424-62a52765c970.jpg)
![img_5062](https://cloud.githubusercontent.com/assets/12401491/11692374/2b10f982-9e6d-11e5-9149-b3df9529fa43.jpg)

**Comment by jwalgran** [comment]
I do not suspect that this is actually a discrepancy between 6 and 6+. The current release of the application waits up to 15 seconds to try any get an accurate location from the GPS before sending the request to the server to fill the "MY TREE MAPS" list.

(This is too long, and should be fixed in a future update)

Have you tried waiting a full 15-20 seconds?

The screenshots show the location status in different states on the two phones, which may help explain the difference in behavior.

6+ location status
<img width="684" alt="screen shot 2015-12-09 at 10 20 29 am" src="https://cloud.githubusercontent.com/assets/17363/11692784/99fe6762-9e5e-11e5-845e-caa5957e814b.png">

6 location status
<img width="681" alt="screen shot 2015-12-09 at 10 20 37 am" src="https://cloud.githubusercontent.com/assets/17363/11692788/9e2a441e-9e5e-11e5-8b5f-ba50334701cf.png">

**Comment by jmorrison1847** [comment]
Interesting, I did not know that. I tried a full 60s test and it never updated.

I checked my security settings, and OpenTreeMap has permission to use my location "While Using the App" as opposed to "Never," so that seems right.

Oddly enough, even if I go into Philly Tree Map, my location icon in the bottom-right hand of the screen spins forever. Something is keeping it from every knowing my location. So it seems your hunch is right, although I don't know what's causing my phone to never update my location.

**Comment by jwalgran** [comment]
To get as clean a test as possible could you try the following on the 6+

1) From the Profile, tap "Switch Accounts" then "Cancel" to effectively log out of the application.
2) Delete OpenTreeMap and reinstall from the App Store
3) Open the app and accept the prompt to use location services.
4) Log In

**Comment by jmorrison1847** [comment]
I followed these steps and unfortunately tried another 60s test with the same results!

**Comment by jmorrison1847** [comment]
I restarted my phone, logged into OpenTreeMap, Clicked through to PhillyTreeMap and it finally loaded my location. I then went back to the maps page and everything loaded correctly immediately. Sorry for this rabbit hole.
