### ISSUE TITLE
"Sorry. There was a problem saving the updated tree photos."

### ISSUE THREAD

**Issue by hadleystein1** [OpenTreeMap/otm-ios#344]
Customer (https://www.opentreemap.org/communitygreening/map/) reported receiving error message on iOS application when trying to upload photos: "Sorry. There was a problem saving the updated tree photos." 

![unnamed](https://cloud.githubusercontent.com/assets/15219245/22426081/f2093fe8-e6cb-11e6-8dfa-f0201d5a61f0.png)

**Comment by RickMohr** [comment]
Betting dollars to donuts it was a user with the "Public" role, who lack permission to add photos on that map:

![image](https://cloud.githubusercontent.com/assets/2162993/22426373/face3ac4-e6cc-11e6-9297-c7ea1da1e849.png)

Currently we let you try to upload the photo even when you lack permission, but that is fixed in the upcoming release.

**Comment by hadleystein1** [comment]
@RickMohr There are three users on the map -- and all are administrators. The map is also not publicly visible, so looks like it might be a bug still? 

https://www.opentreemap.org/communitygreening/management/user-roles/

**Comment by hadleystein1** [comment]
@RickMohr I did not have a problem uploading a photo to the map - and thus cannot reproduce the error message.

**Comment by hadleystein1** [comment]
+1

"Also, several other participants in the workshop couldn't upload the photos. The app would say that it couldn't save the photos. I've reported this before." - TreeFolks Austin

**Comment by jwalgran** [comment]
Based on production log output, it looks like this may be the result of an incorrect max file size being set on the server.
